import type { NavigationItem } from "../types/navigation";

export const NAV_ITEMS: NavigationItem[] = [
  {
    path: "/dashboard",
    label: "Dashboard",
    title: "Dashboard",
    description: "Overview and backend health.",
    section: "Overview",
  },
  {
    path: "/org-units",
    label: "Org Units",
    title: "Org Units",
    description: "Organization units and hierarchy.",
    section: "Workspace Setup",
  },
  {
    path: "/channels",
    label: "Channels",
    title: "Channels",
    description: "Configured channel definitions.",
    section: "Workspace Setup",
  },
  {
    path: "/channel-accounts",
    label: "Channel Accounts",
    title: "Channel Accounts",
    description: "Provider account bindings.",
    section: "Workspace Setup",
  },
  {
    path: "/business-partners",
    label: "Business Partners",
    title: "Business Partners",
    description: "People and company records.",
    section: "Workspace Setup",
  },
  {
    path: "/services",
    label: "Services",
    title: "Services",
    description: "Service catalog and settings.",
    section: "Conversation Design",
  },
  {
    path: "/request-types",
    label: "Request Types",
    title: "Request Types",
    description: "Request type definitions per service.",
    section: "Conversation Design",
  },
  {
    path: "/content-templates",
    label: "Content Templates",
    title: "Content Templates",
    description: "Localized template messages.",
    section: "Conversation Design",
  },
  {
    path: "/flows",
    label: "Flows",
    title: "Flows",
    description: "Flow headers and versions.",
    section: "Conversation Design",
  },
  {
    path: "/flow-steps",
    label: "Flow Steps",
    title: "Flow Steps",
    description: "Step-level flow logic.",
    section: "Conversation Design",
  },
  {
    path: "/sessions",
    label: "Sessions",
    title: "Sessions",
    description: "Bot sessions and statuses.",
    section: "Operations",
  },
  {
    path: "/messages",
    label: "Messages",
    title: "Messages",
    description: "Inbound and outbound traffic.",
    section: "Operations",
  },
  {
    path: "/service-requests",
    label: "Service Requests",
    title: "Service Requests",
    description: "Requests created from conversations.",
    section: "Operations",
  },
  {
    path: "/runtime-test",
    label: "Runtime Test",
    title: "Runtime Test",
    description: "Runtime inbound-message test surface.",
    section: "Operations",
  },
];
