import type { NavigationItem } from "../types/navigation";

export const NAV_ITEMS: NavigationItem[] = [
  {
    path: "/dashboard",
    label: "Dashboard",
    title: "Dashboard",
    description: "Overview and backend health.",
    section: "Overview",
    allowedRoles: ["admin", "user"],
  },
  {
    path: "/org-units",
    label: "Org Units",
    title: "Org Units",
    description: "Organization units and hierarchy.",
    section: "Workspace Setup",
    allowedRoles: ["admin"],
  },
  {
    path: "/client-accounts",
    label: "Client Accounts",
    title: "Client Accounts",
    description: "Create client users and lock access scope.",
    section: "Workspace Setup",
    allowedRoles: ["admin"],
  },
  {
    path: "/channels",
    label: "Channels",
    title: "Channels",
    description: "Configured channel definitions.",
    section: "Workspace Setup",
    allowedRoles: ["admin"],
  },
  {
    path: "/channel-accounts",
    label: "Channel Accounts",
    title: "Channel Accounts",
    description: "Provider account bindings.",
    section: "Workspace Setup",
    allowedRoles: ["admin"],
  },
  {
    path: "/business-partners",
    label: "Business Partners",
    title: "Business Partners",
    description: "People and company records.",
    section: "Workspace Setup",
    allowedRoles: ["admin"],
  },
  {
    path: "/services",
    label: "Services",
    title: "Services",
    description: "Service catalog and settings.",
    section: "Conversation Design",
    allowedRoles: ["admin"],
  },
  {
    path: "/request-types",
    label: "Request Types",
    title: "Request Types",
    description: "Request type definitions per service.",
    section: "Conversation Design",
    allowedRoles: ["admin"],
  },
  {
    path: "/content-templates",
    label: "Content Templates",
    title: "Content Templates",
    description: "Localized template messages.",
    section: "Conversation Design",
    allowedRoles: ["admin"],
  },
  {
    path: "/flows",
    label: "Flows",
    title: "Flows",
    description: "Flow headers and versions.",
    section: "Conversation Design",
    allowedRoles: ["admin"],
  },
  {
    path: "/flow-messages",
    label: "Flow Messages",
    title: "Flow Messages",
    description: "Edit the visible text people receive in the flow.",
    section: "Conversation Design",
    allowedRoles: ["user"],
  },
  {
    path: "/flow-steps",
    label: "Flow Steps",
    title: "Flow Steps",
    description: "Build and inspect the clinic flow step by step.",
    section: "Conversation Design",
    allowedRoles: ["admin", "user"],
  },
  {
    path: "/gemini",
    label: "Gemini Assistant",
    title: "Gemini Assistant",
    description: "Prompt Gemini directly from the dashboard.",
    section: "Operations",
    allowedRoles: ["admin"],
  },
  {
    path: "/sessions",
    label: "Sessions",
    title: "Sessions",
    description: "Bot sessions and statuses.",
    section: "Operations",
    allowedRoles: ["admin"],
  },
  {
    path: "/messages",
    label: "Messages",
    title: "Messages",
    description: "Inbound and outbound traffic.",
    section: "Operations",
    allowedRoles: ["admin"],
  },
  {
    path: "/service-requests",
    label: "Service Requests",
    title: "Service Requests",
    description: "Requests created from conversations.",
    section: "Operations",
    allowedRoles: ["admin", "user"],
  },
  {
    path: "/baileys",
    label: "WhatsApp Pairing",
    title: "WhatsApp Pairing",
    description: "Baileys connection status and QR pairing.",
    section: "Operations",
    allowedRoles: ["admin", "user"],
  },
  {
    path: "/runtime-test",
    label: "Runtime Test",
    title: "Runtime Test",
    description: "Runtime inbound-message test surface.",
    section: "Operations",
    allowedRoles: ["admin"],
  },
];
