import type { NavigationItem } from "../types/navigation";

export const NAV_ITEMS: NavigationItem[] = [
  {
    path: "/dashboard",
    icon: "dashboard",
    label: "Dashboard",
    title: "Dashboard",
    description: "WhatsApp marketing status and setup shortcuts.",
    section: "Overview",
    labelKey: "nav.dashboard.label",
    titleKey: "nav.dashboard.title",
    descriptionKey: "nav.dashboard.description",
    sectionKey: "nav.overview",
    allowedRoles: ["super_admin", "admin", "manager"],
  },
  {
    path: "/users",
    icon: "users",
    label: "Users",
    title: "Users",
    description: "Create dashboard users and manage their roles.",
    section: "Setup",
    labelKey: "nav.users.label",
    titleKey: "nav.users.title",
    descriptionKey: "nav.users.description",
    sectionKey: "nav.setup",
    allowedRoles: ["super_admin"],
  },
  {
    path: "/whatsapp-outreach",
    icon: "send",
    label: "WhatsApp Marketing",
    title: "WhatsApp Marketing",
    description: "Send one approved marketing message to selected WhatsApp contacts.",
    section: "WhatsApp",
    labelKey: "nav.marketing.label",
    titleKey: "nav.marketing.title",
    descriptionKey: "nav.marketing.description",
    sectionKey: "nav.whatsapp",
    allowedRoles: ["super_admin", "admin", "manager"],
  },
  {
    path: "/templates",
    icon: "template",
    label: "Templates",
    title: "Templates",
    description: "Create, preview, and reuse campaign message templates.",
    section: "WhatsApp",
    labelKey: "nav.templates.label",
    titleKey: "nav.templates.title",
    descriptionKey: "nav.templates.description",
    sectionKey: "nav.whatsapp",
    allowedRoles: ["super_admin", "admin", "manager"],
  },
  {
    path: "/contact-sections",
    icon: "contacts",
    label: "Contact Sections",
    title: "Contact Sections",
    description: "Import named contact groups and remember delivery status.",
    section: "WhatsApp",
    labelKey: "nav.contactSections.label",
    titleKey: "nav.contactSections.title",
    descriptionKey: "nav.contactSections.description",
    sectionKey: "nav.whatsapp",
    allowedRoles: ["super_admin", "admin", "manager"],
  },
  {
    path: "/interested-people",
    icon: "leads",
    label: "Interested People",
    title: "Interested People",
    description: "Track replies from people who want an agent follow-up.",
    section: "WhatsApp",
    labelKey: "nav.interestedPeople.label",
    titleKey: "nav.interestedPeople.title",
    descriptionKey: "nav.interestedPeople.description",
    sectionKey: "nav.whatsapp",
    allowedRoles: ["super_admin", "admin", "manager", "viewer"],
  },
  {
    path: "/baileys",
    icon: "pairing",
    label: "WhatsApp Pairing",
    title: "WhatsApp Pairing",
    description: "Connect a WhatsApp device with QR pairing.",
    section: "WhatsApp",
    labelKey: "nav.pairing.label",
    titleKey: "nav.pairing.title",
    descriptionKey: "nav.pairing.description",
    sectionKey: "nav.whatsapp",
    allowedRoles: ["super_admin", "admin"],
  },
  {
    path: "/channel-accounts",
    icon: "accounts",
    label: "WhatsApp Accounts",
    title: "WhatsApp Accounts",
    description: "Create and manage WhatsApp account records.",
    section: "Setup",
    labelKey: "nav.accounts.label",
    titleKey: "nav.accounts.title",
    descriptionKey: "nav.accounts.description",
    sectionKey: "nav.setup",
    allowedRoles: ["super_admin", "admin"],
  },
  {
    path: "/channels",
    icon: "channels",
    label: "Channels",
    title: "Channels",
    description: "Create the WhatsApp channel used by account pairing.",
    section: "Setup",
    labelKey: "nav.channels.label",
    titleKey: "nav.channels.title",
    descriptionKey: "nav.channels.description",
    sectionKey: "nav.setup",
    allowedRoles: ["super_admin", "admin"],
  },
];
